/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthResturantRegisterRouteImport } from './routes/auth/resturant/register'
import { Route as AuthResturantLoginRouteImport } from './routes/auth/resturant/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResturantRegisterRoute = AuthResturantRegisterRouteImport.update({
  id: '/auth/resturant/register',
  path: '/auth/resturant/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResturantLoginRoute = AuthResturantLoginRouteImport.update({
  id: '/auth/resturant/login',
  path: '/auth/resturant/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/resturant/login': typeof AuthResturantLoginRoute
  '/auth/resturant/register': typeof AuthResturantRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/resturant/login': typeof AuthResturantLoginRoute
  '/auth/resturant/register': typeof AuthResturantRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/resturant/login': typeof AuthResturantLoginRoute
  '/auth/resturant/register': typeof AuthResturantRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/auth/resturant/login'
    | '/auth/resturant/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/auth/resturant/login'
    | '/auth/resturant/register'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/auth/resturant/login'
    | '/auth/resturant/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResturantLoginRoute: typeof AuthResturantLoginRoute
  AuthResturantRegisterRoute: typeof AuthResturantRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/resturant/register': {
      id: '/auth/resturant/register'
      path: '/auth/resturant/register'
      fullPath: '/auth/resturant/register'
      preLoaderRoute: typeof AuthResturantRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/resturant/login': {
      id: '/auth/resturant/login'
      path: '/auth/resturant/login'
      fullPath: '/auth/resturant/login'
      preLoaderRoute: typeof AuthResturantLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResturantLoginRoute: AuthResturantLoginRoute,
  AuthResturantRegisterRoute: AuthResturantRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
